# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7a09787ec93787bd03f1716eeaa4990"
name = "lucrative-strategy-app"
application_url = "https://lan-harbour-bidding-myrtle.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "longbd6-hamsa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://lan-harbour-bidding-myrtle.trycloudflare.com/auth/callback",
  "https://lan-harbour-bidding-myrtle.trycloudflare.com/auth/shopify/callback",
  "https://lan-harbour-bidding-myrtle.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
